---

- name: set fact es_same_keystore
  set_fact: es_same_keystore=false

- name: set fact es_same_keystore if stores match
  set_fact: es_same_keystore=true
  when: es_ssl_keystore == es_ssl_truststore

- name: Ensure certificate directory exists
  become: true
  file:
    dest: "{{ es_ssl_certificate_path }}"
    state: directory
    owner: root
    group: "{{ es_group }}"
    mode: "750"
  when: es_ssl_upload

- name: Auto generate SSL certificates
  become: true
  block:
    - name: Set temporary CA path
      ansible.builtin.set_fact:
        temp_ca_path: "{{ es_ssl_certificate_path }}/elastic-stack-ca.p12"

    - name: Checking temporary ElasticSearch CA exists or not
      ansible.builtin.stat:
        path: "{{ temp_ca_path }}"
      register: ca_file

    - name: Generate ElasticSearch CA (temporary)
      ansible.builtin.command: >
        {{ es_home }}/bin/elasticsearch-certutil ca --out {{ temp_ca_path }} --pass {{ es_ssl_truststore_password }}
      when: not ca_file.stat.exists

    - name: Checking ElasticSearch Certificates exists or not
      ansible.builtin.stat:
        path: "{{ es_ssl_certificate_path }}/{{ es_ssl_keystore }}"
      register: cert_file

    - name: Generate certificates (bundled with CA for truststore use)
      ansible.builtin.command: >
        {{ es_home }}/bin/elasticsearch-certutil cert --ca {{ temp_ca_path }} --ca-pass {{ es_ssl_truststore_password }} --out {{ es_ssl_certificate_path }}/{{ es_ssl_keystore }} --pass {{ es_ssl_keystore_password }}
      when: not cert_file.stat.exists

    - name: Fetch ElasticSearch Certificates to local certs dir (used for both key and trust)
      ansible.builtin.fetch:
        src: "{{ es_ssl_certificate_path }}/{{ es_ssl_keystore }}"
        dest: "./{{ es_ssl_keystore }}"
        flat: true

    - name: Clean up temporary CA file
      ansible.builtin.file:
        path: "{{ temp_ca_path }}"
        state: absent
  run_once: true
  when: es_auto_generate_certificates

- name: Upload SSL/TLS keystore
  become: true
  copy:
    src: "{{ es_ssl_keystore }}"
    dest: "{{ es_ssl_certificate_path }}/{{ es_ssl_keystore | basename }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "640"
  when: es_ssl_upload and es_ssl_keystore and es_ssl_truststore
  notify: restart elasticsearch
  register: copy_keystore

- name: Upload SSL/TLS truststore
  become: true
  copy:
    src: "{{ es_ssl_truststore }}"
    dest: "{{ es_ssl_certificate_path }}/{{ es_ssl_truststore | basename }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "640"
  when: es_ssl_upload and es_ssl_keystore and es_ssl_truststore
  notify: restart elasticsearch
  register: copy_truststore

- name: Upload SSL/TLS key and certificate
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ es_ssl_certificate_path }}/{{ item | basename }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "640"
  with_items:
    - "{{ es_ssl_key }}"
    - "{{ es_ssl_certificate }}"
  when: es_ssl_upload and es_ssl_key and es_ssl_certificate
  #Restart if these change
  notify: restart elasticsearch
  register: copy_certificates

- name: Upload SSL Certificate Authority
  become: true
  copy:
    src: "{{ es_ssl_certificate_authority }}"
    dest: "{{ es_ssl_certificate_path }}/{{ es_ssl_certificate_authority | basename }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "640"
  #Restart if this changes
  notify: restart elasticsearch
  when: es_ssl_upload and (es_ssl_certificate_authority is defined) and (es_ssl_certificate_authority|length > 0)

- name: Set keystore password
  become: true
  shell: echo "{{ es_ssl_keystore_password }}" | {{ es_home }}/bin/elasticsearch-keystore add -x -f 'xpack.security.{{ item }}.ssl.keystore.secure_password'
  no_log: True
  when: es_ssl_keystore_password and (copy_keystore.changed or (es_same_keystore and copy_truststore.changed))
  with_items:
    - http
    - transport

- name: Set truststore password
  become: true
  shell: echo "{{ es_ssl_truststore_password }}" | {{ es_home }}/bin/elasticsearch-keystore add -x -f 'xpack.security.{{ item }}.ssl.truststore.secure_password'
  no_log: True
  when: es_ssl_truststore_password and (copy_truststore.changed or (es_same_keystore and copy_keystore.changed))
  with_items:
    - http
    - transport

- name: Remove keystore password
  become: true
  shell: "{{ es_home }}/bin/elasticsearch-keystore remove 'xpack.security.{{ item }}.ssl.keystore.secure_password'"
  when: es_ssl_keystore_password == "" and (copy_keystore.changed or (es_same_keystore and copy_truststore.changed))
  ignore_errors: yes
  with_items:
    - http
    - transport

- name: Remove truststore password
  become: true
  shell: "{{ es_home }}/bin/elasticsearch-keystore remove 'xpack.security.{{ item }}.ssl.truststore.secure_password'"
  when: es_ssl_truststore_password == "" and (copy_truststore.changed or (es_same_keystore and copy_keystore.changed))
  ignore_errors: yes
  with_items:
    - http
    - transport

- name: Set key password
  become: true
  shell: echo "{{ es_ssl_key_password }}" | {{ es_home }}/bin/elasticsearch-keystore add -x -f 'xpack.security.{{ item }}.ssl.secure_key_passphrase'
  no_log: True
  when: es_ssl_key_password and copy_certificates.changed
  with_items:
    - http
    - transport

- name: Remove key password
  become: true
  shell: "{{ es_home }}/bin/elasticsearch-keystore remove 'xpack.security.{{ item }}.ssl.secure_key_passphrase'"
  when: es_ssl_key_password == "" and copy_certificates.changed
  ignore_errors: yes
  with_items:
    - http
    - transport
